project:
  type: website
  resources: [/data-export]
  output-dir: docs

website:
  title: "Mapa státu"
  site-url: https://petrbouchal.xyz/mapa-statu
  navbar:
    left:
      - orgs.qmd
      - analytici.qmd
  page-footer:
    center:
      - text: Kód na Githubu
        href: "https://github.com/petrbouchal/mapa-statu"
    left:
      - text: "Autor: Petr Bouchal"
        href: "https://petrbouchal.xyz"
    right:
      - "2024"
  twitter-card:
    image: opengraph.png
    title: "Mapa státu: přehled veřejných institucí a jejich struktury"
    description: "Podívejte se na organizační struktury českých úřadů a analytické útvary v nich."
  open-graph:
    image: opengraph.png
    title: "Mapa státu: přehled veřejných institucí a jejich struktury"
    description: "Podívejte se na organizační struktury českých úřadů a analytické útvary v nich."
    locale: cs_CZ

format:
  html:
    lang: cs
    language: cs
    theme:
      light: [styles/cosmo.css, styles/styles.scss, styles/legend.css]

