project:
  type: website
  resources: [/data-export]
  output-dir: "docs-pank"

website:
  title: "Mapa státu"
  navbar:
    left:
      - orgs.qmd
      - analytici.qmd
    right:
      - text: "← zpět na PANK"
        href: https://pank.cz
  page-footer:
    center:
      - text: Kód na Githubu
        href: "https://github.com/petrbouchal/mapa-statu"
    left:
      - text: "Autor: Petr Bouchal"
        href: "https://petrbouchal.xyz"
    right:
      - "2024"
  twitter-card:
    image: https://pank.cz/images/opengraph.jpg
    title: "Mapa státu: přehled veřejných institucí a jejich struktury. Součást PANK.cz."
    description: "Podívejte se na organizační struktury českých úřadů a analytické útvary v nich."
  open-graph:
    image: https://pank.cz/images/opengraph.jpg
    title: "Mapa státu: přehled veřejných institucí a jejich struktury. Součást PANK.cz."
    description: "Podívejte se na organizační struktury českých úřadů a analytické útvary v nich."
    locale: cs_CZ

format:
  html:
    lang: cs
    language: cs
    theme:
      light: [styles/cosmo.css, styles/styles-pank.scss, styles/legend.css]

