default:

  export_dir: "data-export"

  # orgchart_xml: "~/cpers/statnisluzba-downloader/soubory-struktura/ISoSS_Opendata_OSYS_OSSS_20220215T020004.xml"
  orgchart_url: "https://portal.isoss.cz/opendata/ISoSS_Opendata_OSYS_OSSS.xml"
  orgchart_xml_local: "/Users/petr/cpers/statnisluzba-downloader/soubory-struktura/ISoSS_Opendata_OSYS_OSSS_20240828T224056.xml"
  orgchart_xml_target: "data-input/orgchart/orgchart.xml"
  orgchart_use_local: true

